# Generated by Django 4.1 on 2022-11-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvt_members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='National',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('President', 'President'), ('Deputy President', 'Deputy President'), ('Cabinet Secretary', 'Cabinet Secretary')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
