# Generated by Django 4.1 on 2022-11-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvt_members', '0003_remove_national_category_alter_national_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='national',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
